# Generated by Django 4.0.6 on 2022-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='emoji',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
