# Generated by Django 4.0.6 on 2022-08-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_post_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
