# Generated by Django 4.0.6 on 2022-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.PositiveIntegerField(default=0, help_text='viewers'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='feed.tag'),
        ),
    ]
